#include "GameTexture.h"
//------------------------------------
void GameTexture::loadTexture()
{
	m_gameOver.loadFromFile("GameOver.png");
	m_youWon.loadFromFile("YouWon.png");
	//------------------------------------------------
	m_font.loadFromFile("C:/Windows/Fonts/Impact.ttf");
	//-------------------------------------------------
	m_menu.loadFromFile("Menu.png");
	//-------------------------------------------------
	m_backround[0].loadFromFile("backround1.png");
	m_backround[1].loadFromFile("backround2.png");
	m_backround[2].loadFromFile("backround3.png");
	m_backround[3].loadFromFile("backround4.png");
	//-------------------------------------------------
	m_hammer.loadFromFile("Hammer.png");
	m_bow.loadFromFile("Bow.png");
	m_demon.loadFromFile("Demon.png");
	m_fireHammer.loadFromFile("FireHammer.png");
	m_electricHammer.loadFromFile("ElectricHammer.png");
	m_axe.loadFromFile("Axe.png");
	m_sowrd.loadFromFile("SowrdAttack.png");
	m_lightBow.loadFromFile("LightBow.png");
	m_Box.loadFromFile("BoxAttack.png");
	m_wing.loadFromFile("WingAttack.png");
	m_kmeama.loadFromFile("Kmeama.png");
	//-------------------------------------------------
	m_deep.loadFromFile("Deep.png");
	m_batTexture.loadFromFile("Bat.png");
	m_dennis.loadFromFile("Dennis.png");
	m_louis.loadFromFile("Louis.png");
	m_julian.loadFromFile("Julian.png");
	//-------------------------------------------------
	m_troll.loadFromFile("Troll.png");
	m_dragon.loadFromFile("Dragon.png");
	m_cow.loadFromFile("Cow.png");
	m_monkey.loadFromFile("Monkey.png");
	//-------------------------------------------------
	m_magicBall.loadFromFile("MagicBall.png");
	m_fireBall.loadFromFile("FireBall.png");
	m_iceBall.loadFromFile("IceBall.png");
	m_batAttack.loadFromFile("BatAttack.png");
	m_skullAttack.loadFromFile("SkullAttack.png");
	//-------------------------------------------------
	m_enemyLifeBar.loadFromFile("EnemyBar.png");
	m_PlayerLifeBar.loadFromFile("PlayerBar.png");
	//-------------------------------------------------
	m_merchantBackround.loadFromFile("MerchantBackround.png");
	m_merchantItem.loadFromFile("MerchantItem.png");
	m_exit.loadFromFile("Exit.png");
	//------------------------------------------------
	m_axeIcon.loadFromFile("Axe_icon.png");
	m_boxIcon.loadFromFile("Box_icon.png");
	m_electricHammerIcon.loadFromFile("electricHammer_icon.png");
	m_fireHammerIcon.loadFromFile("firehammer_icon.png");
	m_iceHammerIcon.loadFromFile("iceHammer_icon.png");
	m_kamehameaIcon.loadFromFile("Kmeahaea_icon.png");
	m_lightBowIcon.loadFromFile("Light_bow_icon.png");
	m_normalBowIcon.loadFromFile("Normal_bow_icon.png");
	m_sowrdIcon.loadFromFile("Sowrd_icon.png");
	m_wingIcon.loadFromFile("Wing_icon.png");
	m_charectersIcon.loadFromFile("charecters.png");
	m_manaBar.loadFromFile("ManaBar.png");
	m_topBrackround.loadFromFile("TopBackround.png");
}